# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDeYxR3c7udzOmo5H18lA9f9aELP2ikO
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello World!')

if st.botton('Generate Random Number'):
  random_number = random.randint(0,100)
  st.write(f'Random Number: {random_number}')